### Boss do Mundo 1 lvl 5 
#### Remoção de duplicatas: Verifique a existência de registros duplicados no DataFrame consolidado e elimine-os para garantir a unicidade dos dados.
#### Remover colunas irrelevantes: Analise as colunas presentes e exclua aquelas que não são relevantes para a análise
#### Tratar valores ausentes: Identifique valores nulos ou ausentes e aplique as ações necessárias para corrigi-los (preenchimento ou remoção).
#### Filtrar Pokémon proibidos: Exclua do conjunto de dados todos os Pokémon que pertencem às seguintes categorias:
#### • Lendários e Sub-lendários
#### • Míticos
#### • Pokémon com Mega Evoluções

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("pokedex_(Update_04.21).csv")

In [3]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1040    False
1041    False
1042    False
1043    False
1044    False
Length: 1045, dtype: bool

In [4]:
df = df.drop_duplicates()

In [5]:
print(df.head())

   Unnamed: 0  pokedex_number           name german_name        japanese_name  \
0           0               1      Bulbasaur     Bisasam  フシギダネ (Fushigidane)
1           1               2        Ivysaur   Bisaknosp   フシギソウ (Fushigisou)
2           2               3       Venusaur    Bisaflor  フシギバナ (Fushigibana)
3           3               3  Mega Venusaur    Bisaflor  フシギバナ (Fushigibana)
4           4               4     Charmander    Glumanda      ヒトカゲ (Hitokage)

   generation  status         species  type_number type_1  ... against_ground  \
0           1  Normal    Seed Pokémon            2  Grass  ...            1.0
1           1  Normal    Seed Pokémon            2  Grass  ...            1.0
2           1  Normal    Seed Pokémon            2  Grass  ...            1.0
3           1  Normal    Seed Pokémon            2  Grass  ...            1.0
4           1  Normal  Lizard Pokémon            1   Fire  ...            2.0

   against_flying  against_psychic  against_bug against_rock against_ghost  \
0             2.0              2.0          1.0          1.0           1.0
1             2.0              2.0          1.0          1.0           1.0
2             2.0              2.0          1.0          1.0           1.0
3             2.0              2.0          1.0          1.0           1.0
4             1.0              1.0          0.5          2.0           1.0

  against_dragon  against_dark  against_steel  against_fairy
0            1.0           1.0            1.0            0.5
1            1.0           1.0            1.0            0.5
2            1.0           1.0            1.0            0.5
3            1.0           1.0            1.0            0.5
4            1.0           1.0            0.5            0.5

[5 rows x 51 columns]

In [6]:
print(df.isnull().sum())

Unnamed: 0            0
pokedex_number        0
name                  0
german_name           0
japanese_name         0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2              492
height_m              0
weight_kg             1
abilities_number      0
ability_1             3
ability_2           529
ability_hidden      232
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate           18
base_friendship     115
base_experience     120
growth_rate           1
egg_type_number       0
egg_type_1            3
egg_type_2          760
percentage_male     173
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [7]:
df = df.dropna()

In [9]:
df = df[~df['status'].isin(['Legendary', 'Sub Legendary', 'Mythical', 'Mega Evolution'])]

df.head()

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
45,45,34,Nidoking,Nidoking,ニドキング (Nidoking),1,Normal,Drill Pokémon,2,Poison,...,2.00,1.0,2.0,0.5,0.5,1.0,1.0,1.0,1.0,0.5
59,59,46,Paras,Paras,パラス (Paras),1,Normal,Mushroom Pokémon,2,Bug,...,0.25,4.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0
60,60,47,Parasect,Parasek,パラセクト (Parasect),1,Normal,Mushroom Pokémon,2,Bug,...,0.25,4.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0
103,103,79,Slowpoke,Flegmon,ヤドン (Yadon),1,Normal,Dopey Pokémon,2,Water,...,1.00,1.0,0.5,2.0,1.0,2.0,1.0,2.0,0.5,1.0
105,105,80,Slowbro,Lahmus,ヤドラン (Yadoran),1,Normal,Hermit Crab Pokémon,2,Water,...,1.00,1.0,0.5,2.0,1.0,2.0,1.0,2.0,0.5,1.0